[colors]
ansi = [
  '#000000',
  '#ff8059',
  '#44bc44',
  '#d0bc00',
  '#2fafff',
  '#feacd0',
  '#00d3d0',
  '#a6a6a6'
]
brights = [
  '#595959',
  '#f08b50',
  '#00c06f',
  '#c0c530',
  '#79a8ff',
  '#b6a0ff',
  '#6ae4b9',
  '#ffffff'
]

cursor_bg = '#ffffff'
cursor_fg = '#000000'
cursor_border = '#ffffff'

background = '#000000'
foreground = '#ffffff'

selection_bg = '#3c3c3c'
selection_fg = '#ffffff'

[metadata]
name = 'modus-vivendi'
author = 'zibebe'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/modus-vivendi-theme.el'
