[colors]
ansi = [
  '#000000',
  '#a60000',
  '#006800',
  '#6f5500',
  '#0031a9',
  '#721045',
  '#005e8b',
  '#a6a6a6'
]
brights = [
  '#595959',
  '#972500',
  '#00663f',
  '#884900',
  '#3548cf',
  '#531ab6',
  '#005f5f',
  '#ffffff'
]

cursor_bg = '#000000'
cursor_fg = '#ffffff'
cursor_border = '#000000'

background = '#ffffff'
foreground = '#000000'

selection_bg = '#bdbdbd'
selection_fg = '#000000'

[metadata]
name = 'modus-operandi'
author = 'zibebe'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/modus-operandi-theme.el'
